---
title: "ACII Model3 - Performance"
author: "Fettah Kiran"
date: "`r Sys.Date()`"
output: pdf_document
toc: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r include=FALSE}

library(tidyverse)
library(lubridate)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(readr)
library(gridExtra)
library(dplyr)
library(tidyr)
library(knitr)
library(MASS)
library("car")
library(lme4)
library(lmerTest)
library(lattice)
library(sjPlot)
library(Matrix)
library(arm)  # display() # convenience functions for regression in R

```


```{r include=FALSE}

#rm(list = ls())
dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(dir)
getwd()

dataDir <- "../data/"
Qlevel<- read.csv(paste0("../data/ACII_ModelData_N20.csv"),stringsAsFactors = T, header=T,sep=",")

# paper.col.names <- c("ParticipantID","Gender","pp.mean","pp.log.mean","HR.E4.mean","HR.E4.validated.mean","HR.AW.mean", "pp_normalized","pp_log_normalized", "hr.e4_normalized","hr.e4_validated_normalized", "hr.aw_normalized",
# "SAI.Score", "Question.Name","Question.Type", "Question.Order","Question.Number","q.solv.time","grade" )
# 
# #reoder columns based on the description of ACII23 paper.
# Qlevel <- Qlevel[paper.col.names]

# colnames(Qlevel)

# Save the Qlevel data with new column orders
#write.csv(Qlevel,"../data/ACII_ModelData_N20.csv", row.names =F)

```


```{r echo=FALSE}

#colSums(!is.na(SLevel))
PP.len = colSums(!is.na(Qlevel))[["pp.log.mean"]]
HR.len = colSums(!is.na(Qlevel))[["HR.E4.mean"]] 
HR.Perf.len = colSums(!is.na(Qlevel))[["hr.e4_validated_normalized"]] 

HR.Perf.len = colSums(!is.na(Qlevel))[["hr.e4_validated_normalized"]]


AW.len = colSums(!is.na(Qlevel))[["HR.AW.mean"]] 

pId.len =length(unique(Qlevel$ParticipantID)) 
pp.pId.len =length(unique(Qlevel$ParticipantID)) - 1 


W.len = table(Qlevel$Question.Type)[['W']]
A.len = table(Qlevel$Question.Type)[['A']]
V.len = table(Qlevel$Question.Type)[['V']]

HR.W.len = table(Qlevel[!is.na(Qlevel$HR.E4.validated.mean),]$Question.Type)[['W']]
HR.A.len = table(Qlevel[!is.na(Qlevel$HR.E4.validated.mean),]$Question.Type)[['A']]
HR.V.len = table(Qlevel[!is.na(Qlevel$HR.E4.validated.mean),]$Question.Type)[['V']]

```


```{r echo=FALSE, message=FALSE, warning=FALSE}

# Base gender F
Qlevel_rl <- within(Qlevel, Gender<- relevel(Gender, ref = "F") )

# Base Question.Type V
Qlevel_rl$Question.Type <- factor(Qlevel_rl$Question.Type)
Qlevel_rl <- within(Qlevel, Question.Type<- relevel(Question.Type, ref = "V") )


```


# Model 3 - Performance Model

```{r echo=FALSE}

#setwd("......")   ### folder with the data
#getwd()

### Here we will load the available data 
tmpD<-read.csv(paste0("../data/ACII_ModelData_N20.csv"),header=T,sep=",")

#tmpD<-Qlevel

#dim(tmpD)

VarNames0<-names(tmpD)

# VarNames_paper <-c("S","Gender","PPMean","PPlogMean","HRE4Mean","HRE4ValidMean","HRAWMean","PPNorm","PPlogNorm","HRE4Norm","HRE4ValidNorm","HRAWNorm",      "SAI","QName","QType","QOrder","QNumber","QSolTime","Grade")

VarNames<-c("S","QName","QType","QOrder","QNumber","QSolTime","Grade",
            "PPMean","PPlogMean","HRE4Mean","HRE4ValidMean","HRAWMean","PPNorm",
            "PPlogNorm","HRE4Norm","HRE4ValidNorm","HRAWNorm","Gender","SAI" )


##############################################################
##############################################################
##############################################################
### MODEL (A)
### HERE WE WILL EXAMINE THE FIRST OF THE RESPONSE VARIABLES: 
### Grade WHICH IS BINARY
##############################################################
##############################################################
##############################################################

### Response variable is Grade, i.e. if it Pass (1) or not (0) 
### the question of the test
Grade<-tmpD[,7]
#table(Grade)

### Explanatory Variables
tmp1<-1:dim(tmpD)[2]
tmp1<-tmp1[-7]
X<-tmpD[,tmp1]      ### The explanatory variables that will be used in the modeling
Xnames0<-VarNames0[tmp1]  ### The names of the explanatory variables
Xnames<-VarNames[tmp1]  ### The names of the explanatory variables


### Here we will define the Categorical and Numerical values for the 
### specific response that we examine. These variables refer to X (not tmpD)
### The following are the categorical explanatory variable
tmpCAT<-c(2:3,17)
### The following are the numerical explanatory variable
tmpNUM<-c(4:16,18)

### Here we define the Subjects that participated in the study, which will
### form the random effects
SubNames<-unique(X[,1])
Sub<-factor(X[,1])

### Here we name the variables to use them in the model
for (i in tmpCAT){
  assign(paste(Xnames[i]),as.factor(X[,i]))
}
for (i in tmpNUM){
  assign(paste(Xnames[i]),X[,i])
}

### Here we will put Video in QType to be the baseline
QType<-factor(QType,levels = c("V","A","W"))


### Here we scale the variables for the Generalized Model
sQSolTime<-scale(QSolTime)
sPPlogMean<-scale(PPlogMean)
sPPlogNorm<-scale(PPlogNorm)
sHRE4ValidMean<-scale(HRE4ValidMean)
sHRE4ValidNorm<-scale(HRE4ValidNorm)
sSAI<-scale(SAI)

Grade<-factor(Grade)



```


## Full Model
```{r echo=FALSE}

#########################################################################
### Modeling Grade vs fixed effects and  Normalized-type stress variables
#########################################################################
FullModel<-glmer(Grade~1+QType+sQSolTime+sPPlogNorm+sHRE4ValidNorm+sSAI 
                 +(1|QName),family=binomial)

summary(FullModel)

cat("\n ******** FullModel_unscaled *********** \n")

FullModel_unscaled<-glmer(Grade~1+QType+QSolTime+PPlogNorm+HRE4ValidNorm+SAI
                 +(1|QName),family=binomial)
summary(FullModel_unscaled)



```


```{r}
anova(FullModel,FullModel_unscaled)
```

\newpage
## Manual Optimization
## Remove sPPlogNorm 
```{r echo=FALSE}
FM<-glmer(Grade~1+QType+sQSolTime+sHRE4ValidNorm+sSAI
                 +(1|QName),family=binomial)
summary(FM)
#anova(FM)
#FM = FullModel

```

## Remove sHRE4ValidNorm -> Optimal(N=20)
```{r echo=FALSE}
FM<-glmer(Grade~1+QType+sQSolTime+sSAI
                 +(1|QName),family=binomial)
summary(FM)


```



## Remove QType 
```{r echo=FALSE}
FM<-glmer(Grade~1+sQSolTime+sSAI
                 +(1|QName),family=binomial)
summary(FM)
anova(FM)
```



\newpage
## Optimal Model Plots

```{r echo=FALSE}
#FM<-glmer(Grade~1+QType+sQSolTime+sSAI +(1|QName),family=binomial)
FM<-glmer(Grade~1+sQSolTime+sSAI+(1|QName),family=binomial)
summary(FM)
anova(FM)

aic.bw<- AIC(FM)

cat("\nOptimal Model of Manual Elimination AIC:" ,aic.bw , "\n\n")

#aic.full
cat("Full Model AIC:" ,AIC(FullModel))
```

\newpage


```{r echo=FALSE}
# Solving Time
#library(latex2exp)
qst.pm <- plot_model(FM, 
             type = "pred", 
             terms = "sQSolTime",
             dot.size = 6,
             line.size = 2,
             title = "Question Time")+ 
        aes(color = "sQSolTime") +
        scale_color_manual(values = "red") +
        geom_vline(
          xintercept = mean(sQSolTime),
          linetype = "dashed",
          color = "gray",
          size = 1
        )+  theme_bw()+
        theme(panel.grid = element_blank(),
              axis.title.y = element_blank(),
              plot.title = element_text(hjust = 0.5,  face = "bold"), 
              axis.text.x = element_text(size = 10, face = "bold"),
               axis.text.y = element_blank(),#element_text(size = 10, face = "bold"),
              axis.ticks.y = element_blank(),
              legend.position = "none"
            )+ labs(x="", y="") 


sai.pm<-plot_model(FM, 
             type = "pred", 
             terms = "sSAI",
             dot.size = 6,
             line.size = 2,
             title = "Pre-exam Anxiety Score")+ 
          aes(color = "sSAI") +
        scale_color_manual(values = "red") +
        geom_vline(
          xintercept = mean(sSAI),
          linetype = "dashed",
          color = "gray",
          size = 1
        )+  theme_bw()+
        theme(panel.grid = element_blank(),
              # axis.title.y = element_blank(),
              plot.title = element_text(hjust = 0.5, face = "bold"), 
              axis.text.x = element_text(size = 10, face = "bold"),
              axis.text.y = element_text(size = 10, face = "bold"),
              legend.position = "none"
              )+ labs(x="", y=expression(paste(bolditalic("P(QG)")))) +
  scale_y_continuous(limits  = c(0,1), labels = scales::percent)
```

```{r,echo=FALSE, warning=FALSE}

# Create the significances legend
library(cowplot)
levels = c("B", "C")
num = c( 10, 15)
ymin = c( 0, 0)
ymax = c( 2, 3)

Legend_DF = data.frame(levels, num, ymin, ymax)

plot <- ggplot(Legend_DF, aes(x = levels, y = num, colour = levels)) +
  geom_errorbar(aes(ymin = ymin, ymax = ymax), size = 1.1) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    axis.text.x = element_text(face = "bold", size = 10),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.title = element_blank(),
    legend.key.width = unit(2, 'cm'),
    legend.text = element_text(size = 20)
  ) +
  theme(axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_manual(
    values = c("black", "red"),
    #values = c("black", "#ee9a00", "red"),
    breaks = c("B", "C"),
    labels = c("NS     ", "***")
  ) 
# print(plot)

mylegend = get_legend(plot)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
pred.final <- cowplot::plot_grid(sai.pm,qst.pm, nrow = 1,
      scale = c(.97, .97),
      labels = c("c", "d"),
      label_size = 20
      )

final_plot =  cowplot::plot_grid(pred.final,mylegend,
                                 nrow=2, 
                                 rel_heights = c(.9,.1))
final_plot

filename <- "Grade_FinalModel_Pred_N20.pdf"
plot_dir = "../plots/"
full_path <- file.path(plot_dir, filename)
#ggsave(full_path,  final_plot)

```


```{r echo=FALSE}
### Here we will plot the random effects
re.plot<-plot_model(FM,"re")
re.plot

filename <- "Grade_FinalModel_RE_N20.pdf"
plot_dir = "../plots/"
full_path <- file.path(plot_dir, filename)
#ggsave(full_path,  re.plot)
```
